coverage:
  status:
    project: #add everything under here, more options at https://docs.codecov.com/docs/commit-status
      default:
        # basic
        target: auto #default
        base: auto 
comment: # this is a top-level key
  layout: "header, files, footer" # remove "new" from "header" and "footer"
  hide_project_coverage: false # set to false
github_checks: false